### PR TITLE
swift-driver: correct the legacy driver path construction

### PR DESCRIPTION
**Pull request by compnerd**
Use `URL` to compute the new executable name. This is important to ensure that we correctly strip the executable suffix and re-apply it in the proper location if applicable. Without this change, on Windows, the fallback path would generate `swiftc.exe-legacy-driver` rather than `swiftc-legacy-driver.exe` for the basename of the C++ driver.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/swiftlang/swift/pull/77857

@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Review by artemcm — APPROVED** [review]

**Comment by tshortli** [comment]
@artemcm @compnerd is it possible this is related to `Interpreter/shebang-env.swift` failing on macOS and Linux smoke testing?

https://ci.swift.org/job/swift-PR-Linux/18443/console
https://ci.swift.org/job/swift-PR-macos/18840/console

**Comment by al45tair** [comment]
I've merged the revert because it looks like this broke PR testing.

**Pull request merged**
