### PR TITLE
Windows: simplify the linker invocation for Windows

### PR DESCRIPTION
**Pull request by compnerd**
Rewrite some of the LLD requirement checking code to be simpler to follow. Adjust the C++ interop checking code to be less verbose. Rely on the clang driver to properly select the flags for the profiling runtime.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Review by artemcm — APPROVED** [review]
Looks like good cleanup to me. Thanks!

**Pull request merged**
